server:
  port: 7005
spring:
  application:
    name: nacos-orderServer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #nacos端口地址
  datasource:
    url: jdbc:mysql://localhost:3306/pushsprce
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false